# name: Display Secrets

# on:
#   push:
#     branches:
#       - main

# jobs:
#   display-secrets:
#     runs-on: ubuntu-latest
#     environment: test

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Display Secrets
#       run: |
#         echo "REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}"
#         echo "REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}"

name: Reusable Workflow

on: workflow_call

jobs:
  example_job:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Secrets
        run: |
          echo "REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}"
          echo "REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}"
          ls -lrt ./.
