name: Display Secrets

on:
  push:
    branches:
      - main

jobs:
  display-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Secrets
      run: |
        echo "REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}"
